### ISSUE TITLE
Conflict with mizzao:bootstrap-3

### ISSUE THREAD

**Issue by MichelFloyd** [ajduke/meteor-boostrap-tokenfield#2]
This package also installs ian:bootstrap-3 which then causes a conflict with mizzao:bootstrap-3. Perhaps not a bug but worthwhile noting that only one bootstrap-3 plugin is required.

**Comment by MichelFloyd** [comment]
Thanks adjuke!

I ended up just removing mizzao:bootstrap-3 and things are just working fine. It’s just something that might bite other people and if they don’t figure it out they might uninstall token field (which works great btw!)

Michel

**Comment by ajduke** [comment]
Done.. Pushed to atmosphere.
Making `mizzao:bootstrap-3` as default one as i found most people use it.

**Comment by MichelFloyd** [comment]
Nice work!!
