### ISSUE TITLE
Use official integration of Bootstrap 3

### ISSUE THREAD

**Issue by liaujianjie** [ajduke/meteor-boostrap-tokenfield#5]
Use package `twbs:bootstrap` instead of `mizzao:bootstrap-3`. `twbs:bootstrap` is now the official integration of bootstrap 3.

**Comment by liaujianjie** [comment]
I went ahead an made a pull request: https://github.com/ajduke/meteor-boostrap-tokenfield/pull/6

**Comment by artitw** [comment]
+1

**Comment by newtux** [comment]
+1

**Comment by ajduke** [comment]
Done
